name: Test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and Run
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --verbose